In [ ]:
#!ls /content/drive/MyDrive/cvproject/data/image

origin.7z.001  origin.7z.003  origin.7z.005  origin.7z.007
origin.7z.002  origin.7z.004  origin.7z.006  origin.7z.008


In [ ]:
#!7za -y x "/content/drive/MyDrive/cvproject/data/image/origin.7z.*"


7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.20GHz (406F0),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan /content/drive/MyDrive/cvproject/data/image/                                                      8 files, 8113576419 bytes (7738 MiB)
  0%    
Extracting archive: /content/drive/MyDrive/cvproject/data/image/origin.7z.001
--
Path = /content/drive/MyDrive/cvproject/data/image/origin.7z.001
Type = Split
Physical Size = 1048576000
Volumes = 8
Total Physical Size = 8113576419
----
Path = origin.7z
Size = 8113576419
--
Path = origin.7z
Type = 7z
Physical Size = 8113576419
Headers Size = 863607
Method = LZMA:25
Solid = +
Blocks = 2

  0%      0% - origin/afraid_African_214.jpg                  

In [ ]:
# !cp -r ./origin "/content/drive/MyDrive/cvproject"

In [2]:
label_file_path =r"/content/drive/MyDrive/cvproject/data/label/label.lst"
images_file_name =r"/content/drive/MyDrive/cvproject/origin"

In [3]:
from os.path import split
import pandas as pd
df_info = pd.read_csv(label_file_path , sep=" " , header=None)
col_names ="image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_cofidence expression_label".split()
df_info.columns = col_names
df_info.head()

image_name  face_id_in_image  face_box_top  face_box_left  \
0  angry_actor_104.jpg                 0            28            113   
1  angry_actor_109.jpg                 0            31            157   
2  angry_actor_120.jpg                 1            53             53   
3   angry_actor_13.jpg                 0            77             51   
4  angry_actor_132.jpg                 0            95             31   

   face_box_right  face_box_bottom  face_box_cofidence  expression_label  
0             226              141             22.9362                 0  
1             345              219             50.3056                 0  
2             372              372             13.9434                 2  
3             362              388             85.8104                 3  
4             412              476             82.3948                 0

In [4]:
import pandas as pd

col_names = "image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_confidence expression_label".split()
df_info.columns = col_names
df_sel = df_info[df_info.face_box_confidence > 45]

df_sel.head()


image_name  face_id_in_image  face_box_top  face_box_left  \
1  angry_actor_109.jpg                 0            31            157   
3   angry_actor_13.jpg                 0            77             51   
4  angry_actor_132.jpg                 0            95             31   
5  angry_actor_137.jpg                 0            93            468   
9  angry_actor_150.jpg                 0            56            263   

   face_box_right  face_box_bottom  face_box_confidence  expression_label  
1             345              219              50.3056                 0  
3             362              388              85.8104                 3  
4             412              476              82.3948                 0  
5             842              467              88.9519                 0  
9             376              169              81.8792                 0

In [5]:
df_sel.shape

(51856, 8)

In [6]:
df_sel.image_name.value_counts()

awe_teacher_108.jpg              112
astound_expression_526.jpg        52
awe_grandfather_256.jpg           50
astound_expression_400.jpg        48
amazed_president_890.jpg          46
                                ... 
expressionless_wife_880.jpg        1
expressionless_woman_139.jpg       1
expressionless_worker_310.jpg      1
expressionless_worker_328.jpg      1
surprised_expression_394.jpg       1
Name: image_name, Length: 40628, dtype: int64

In [43]:
import os
import cv2
a=[]
b=[]
for x, row in df_sel.sample(25000).iterrows():
   img_name=row["image_name"]
   a1=row["face_box_left"]
   a2=row["face_box_right"]
   b1=row["face_box_top"]
   b2=row["face_box_bottom"]
   label=row["expression_label"]
   img_path=os.path.join(images_file_name,img_name)

   image = cv2.imread(img_path)

   if image is not None:
      cropped=image[b1:b2, a1:a2]
      face = cv2.resize(cropped, (65, 65))
      if face is not None:
           a.append(face)
           b.append(label)





In [44]:
len(a)

21419

In [45]:
len(b)

21419

In [46]:

import numpy as np
a=np.array(a)


In [48]:
a

array([[[[ 94,  94, 240],
         [ 87,  85, 234],
         [ 87,  86, 237],
         ...,
         [115, 100, 255],
         [112,  98, 255],
         [105,  93, 250]],

        [[ 85,  88, 232],
         [ 86,  85, 231],
         [ 87,  85, 235],
         ...,
         [116,  99, 255],
         [115,  99, 254],
         [111,  97, 251]],

        [[ 86,  86, 235],
         [ 88,  86, 234],
         [ 90,  88, 238],
         ...,
         [113,  99, 254],
         [113,  99, 254],
         [111,  96, 249]],

        ...,

        [[ 68,  90, 120],
         [ 85, 106, 147],
         [ 84, 106, 147],
         ...,
         [ 54,  53, 203],
         [ 58,  56, 208],
         [ 61,  59, 212]],

        [[ 76, 101, 133],
         [ 74,  97, 136],
         [ 89, 113, 153],
         ...,
         [ 52,  51, 201],
         [ 57,  55, 207],
         [ 60,  58, 211]],

        [[ 74, 100, 134],
         [ 94, 119, 156],
         [104, 130, 168],
         ...,
         [ 51,  50, 200],
        

In [49]:
b=np.array(b)
b

array([3, 5, 6, ..., 3, 6, 6])

In [50]:

a.shape

(21419, 65, 65, 3)

In [51]:
b.shape

(21419,)

In [52]:
def convert_to_grayscale(image):
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return gray_image

In [53]:
normalized_a = a/255.0
normalized_a

array([[[[0.36862745, 0.36862745, 0.94117647],
         [0.34117647, 0.33333333, 0.91764706],
         [0.34117647, 0.3372549 , 0.92941176],
         ...,
         [0.45098039, 0.39215686, 1.        ],
         [0.43921569, 0.38431373, 1.        ],
         [0.41176471, 0.36470588, 0.98039216]],

        [[0.33333333, 0.34509804, 0.90980392],
         [0.3372549 , 0.33333333, 0.90588235],
         [0.34117647, 0.33333333, 0.92156863],
         ...,
         [0.45490196, 0.38823529, 1.        ],
         [0.45098039, 0.38823529, 0.99607843],
         [0.43529412, 0.38039216, 0.98431373]],

        [[0.3372549 , 0.3372549 , 0.92156863],
         [0.34509804, 0.3372549 , 0.91764706],
         [0.35294118, 0.34509804, 0.93333333],
         ...,
         [0.44313725, 0.38823529, 0.99607843],
         [0.44313725, 0.38823529, 0.99607843],
         [0.43529412, 0.37647059, 0.97647059]],

        ...,

        [[0.26666667, 0.35294118, 0.47058824],
         [0.33333333, 0.41568627, 0.57647059]

In [54]:
normalized_a.shape

(21419, 65, 65, 3)

In [55]:
a_new=normalized_a.reshape(-1,65*65*3)

In [56]:
a_new

array([[0.36862745, 0.36862745, 0.94117647, ..., 0.23137255, 0.22352941,
        0.82352941],
       [0.12941176, 0.18039216, 0.21176471, ..., 0.10196078, 0.16078431,
        0.17254902],
       [0.23921569, 0.2745098 , 0.35294118, ..., 0.02745098, 0.02745098,
        0.02745098],
       ...,
       [0.03137255, 0.19215686, 0.16078431, ..., 0.10980392, 0.20784314,
        0.38039216],
       [0.09803922, 0.09019608, 0.09019608, ..., 0.48627451, 0.62745098,
        0.84705882],
       [0.10196078, 0.2       , 0.30196078, ..., 0.        , 0.05490196,
        0.17254902]])

In [57]:

a_new.shape

(21419, 12675)

In [58]:
import pandas as pd
pd.Series(b).value_counts()

3    8560
6    6686
4    2235
5    1674
0    1003
1     986
2     275
dtype: int64

In [59]:
a_new.shape

(21419, 12675)

In [60]:
b.shape

(21419,)

In [1]:
from imblearn.over_sampling import SMOTE
sampler=SMOTE()
a_smote, b_smote= sampler.fit_resample(a_new, b)

NameError: ignored

In [ ]:
print(type(a_smote))
print(type(b_smote))

In [ ]:
a_smote

In [31]:
b_smote

array([4, 6, 3, ..., 6, 6, 6])

In [32]:
pd.Series(b_smote).value_counts()

4    339
6    339
3    339
5    339
0    339
2    339
1    339
dtype: int64

In [33]:
a=a_smote.reshape(-1,65,65,3)

In [34]:

a

array([[[[0.80784314, 0.84313725, 0.89803922],
         [0.60392157, 0.65098039, 0.70588235],
         [0.41960784, 0.46666667, 0.5372549 ],
         ...,
         [0.43529412, 0.46666667, 0.58039216],
         [0.50980392, 0.54901961, 0.63921569],
         [0.63137255, 0.67843137, 0.75294118]],

        [[0.75686275, 0.79215686, 0.84705882],
         [0.56078431, 0.60784314, 0.66666667],
         [0.28627451, 0.33333333, 0.40392157],
         ...,
         [0.43921569, 0.4745098 , 0.58823529],
         [0.44313725, 0.48235294, 0.57647059],
         [0.63921569, 0.68235294, 0.75686275]],

        [[0.75686275, 0.79215686, 0.84705882],
         [0.30588235, 0.35294118, 0.40784314],
         [0.50588235, 0.55294118, 0.62352941],
         ...,
         [0.44313725, 0.47843137, 0.58823529],
         [0.34509804, 0.38431373, 0.4745098 ],
         [0.58823529, 0.63529412, 0.70980392]],

        ...,

        [[0.67058824, 0.50980392, 0.45098039],
         [0.6745098 , 0.52941176, 0.46666667]

In [35]:
import numpy as np
from keras.utils import to_categorical
onehot_encoded_b = to_categorical(b)
print(onehot_encoded_b) # Display the one-hot encoded representation


[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [36]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder



a_train, a_temp, b_train, b_temp = train_test_split(normalized_a, onehot_encoded_b, test_size=0.3, random_state=42)
a_val, a_test, b_val, b_test = train_test_split(a_temp, b_temp, test_size=0.5, random_state=42)

#a_train, a_temp, b_train, b_temp = train_test_split(normalized_a, onehot_encoded_b, size=0.4, random_state=54)
#a_value,a_test, b_value, b_test =train_test_split(a_temp, b_temp, test_size=0.6,random_state=54)
print("training set size:",len(a_train))
print("testing set size:",len(a_test))
print("validation set size:",len(a_val))


training set size: 613
testing set size: 132
validation set size: 131


In [37]:

import numpy as np
from keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.3,
    height_shift_range=0.3,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')

datagen.fit(a_train)

#datagen.fit(a_train) # fit the ImageDataGenerator on the training data
augumented_data_generator= datagen.flow(a_train, b_train, batch_size=32)



In [38]:

a_train

array([[[[0.27843137, 0.24705882, 0.23529412],
         [0.27843137, 0.25098039, 0.23921569],
         [0.27843137, 0.25490196, 0.25490196],
         ...,
         [0.63921569, 0.68627451, 0.71372549],
         [0.62352941, 0.69803922, 0.7372549 ],
         [0.64705882, 0.69803922, 0.72156863]],

        [[0.27843137, 0.25098039, 0.23921569],
         [0.28235294, 0.25098039, 0.25098039],
         [0.25882353, 0.23921569, 0.24313725],
         ...,
         [0.66666667, 0.70980392, 0.72941176],
         [0.63921569, 0.69803922, 0.74509804],
         [0.65490196, 0.70196078, 0.73333333]],

        [[0.27843137, 0.25098039, 0.23921569],
         [0.28627451, 0.25098039, 0.24313725],
         [0.28235294, 0.2627451 , 0.25882353],
         ...,
         [0.65882353, 0.70588235, 0.72156863],
         [0.63921569, 0.69411765, 0.74117647],
         [0.6627451 , 0.70980392, 0.7372549 ]],

        ...,

        [[0.28235294, 0.21568627, 0.45098039],
         [0.2627451 , 0.20784314, 0.45490196]

In [39]:

b_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [42]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D,Dense, Flatten
model= Sequential() # create Convolutional Neural Network Model
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(65, 65, 3))) # add 1st convolutional layer
model.add(MaxPooling2D(pool_size=(3, 3))) # add 1st maxpooling layer
model.add(Conv2D(65,(3,3),activation='relu'))# add 1st convolutional layer
model.add(MaxPooling2D(pool_size=(3,3))) # add 2nd maxpooling layer
model.add(Flatten())
model.add(Dense(129, activation= 'relu')) # add fully connected layer
num_of_classes = 7
model.add(Dense(num_of_classes,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy']) # compile the model
history = model.fit(a_train, b_train, epochs=100, batch_size=32, validation_data=(a_val, b_val))
# train the model


58889256/58889256 [==============================] - 1s 0us/step
Epoch 1/100
20/20 [==============================] - 44s 2s/step - loss: 1.6375 - accuracy: 0.4062 - val_loss: 1.6040 - val_accuracy: 0.4427
Epoch 2/100
20/20 [==============================] - 37s 2s/step - loss: 1.2872 - accuracy: 0.5171 - val_loss: 1.6276 - val_accuracy: 0.4046
Epoch 3/100
20/20 [==============================] - 42s 2s/step - loss: 1.1720 - accuracy: 0.5644 - val_loss: 1.5815 - val_accuracy: 0.4656
Epoch 4/100
20/20 [==============================] - 42s 2s/step - loss: 1.0467 - accuracy: 0.6150 - val_loss: 1.6022 - val_accuracy: 0.4275
Epoch 5/100
20/20 [==============================] - 41s 2s/step - loss: 0.9263 - accuracy: 0.6558 - val_loss: 1.6533 - val_accuracy: 0.4275
Epoch 6/100
20/20 [==============================] - 41s 2s/step - loss: 0.8330 - accuracy: 0.7243 - val_loss: 1.6753 - val_accuracy: 0.4351
Epoch 7/100
20/20 [==============================] - 42s 2s/step - loss: 0.7652 - accurac

KeyboardInterrupt: ignored